# Generated by Django 5.0.3 on 2024-03-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0004_room_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(null=True, upload_to='room_images/'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='contact_info',
            field=models.CharField(default='', max_length=100),
        ),
    ]
