# Generated by Django 5.0.3 on 2024-04-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0009_alter_blog_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sklad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(default='Название продукта', max_length=100)),
                ('kol_vo', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('edin', models.CharField(default='Единицы измерения', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(default='Заголовок', max_length=100),
        ),
    ]
